apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timezone-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jbaravinda/timezone-deploy.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
